project:
  type: book
  output-dir: docs

bibliography: library/references.bib
date: last-modified
date-format: "MMM YYYY"

book:
  title: "RNA-Seq System"
  subtitle: "From Raw Reads to Defensible Biological Claims"

  chapters:
    - index.qmd

    - part: "Foundations"
      chapters:
        - 00-preface.qmd
        - 01-system-overview.qmd
        - 02-study-design-and-metadata.qmd
        - 03-environment-and-project-setup.qmd

    - part: "Data Generation & Processing"
      chapters:
        - 04-raw-read-quality-control.qmd
        - 05-read-processing-and-quantification.qmd
        - 06-quantification-and-count-matrix.qmd

    - part: "Expression Analysis"
      chapters:
        - 07-count-quality-assessment-and-filtering.qmd
        - 08-normalization-and-exploratory-analysis.qmd
        - 09-differential-expression-analysis.qmd
        - 10-results-quality-assessment-and-visualization.qmd

    - part: "Biological Interpretation"
      chapters:
        - 11-functional-enrichment-analysis.qmd
        - 12-from-results-to-biological-claims.qmd

    - part: "Reproducible Reporting"
      chapters:
        - 13-reproducible-rnaseq-report.qmd
        - 14-summary-and-next-steps.qmd

  appendices:
    - 999-appendix.qmd
    - 999-references.qmd


format:
  html:
    toc: true
    toc-depth: 3
    number-sections: false
    number-depth: 2
    smooth-scroll: true
    anchor-sections: true
    link-external-icon: true
    css: assets/css/cdi.css
    code-fold: true
    mermaid:
      theme: forest

execute:
  echo: true
  warning: false
  message: false
  freeze: auto
  working-dir: .

